module.exports = [
  { value: '', label: 'Category' },
  { value: 'Medical', label: 'Medical' },
  { value: 'Volunteer', label: 'Volunteer' },
  { value: 'Emergencies', label: 'Emergencies' },
  { value: 'Education', label: 'Education' },
  { value: 'Memorials', label: 'Memorials' },
  { value: 'Sports', label: 'Sports' },
  { value: 'Animals', label: 'Animals' },
  { value: 'Business', label: 'Business' },
  { value: 'Charity', label: 'Charity' },
  { value: 'Community', label: 'Community' },
  { value: 'Competitions', label: 'Competitions' },
  { value: 'Creative', label: 'Creative' },
  { value: 'Events', label: 'Events' },
  { value: 'Faith', label: 'Faith' },
  { value: 'Family', label: 'Family' },
  { value: 'News', label: 'News' },
  { value: 'Newlyweds', label: 'Newlyweds' },
  { value: 'Travel', label: 'Travel' },
  { value: 'Wishes', label: 'Wishes' },
  { value: 'Other', label: 'Other' }
];
